---
- name: install zabbix from the repository
  apt: name=zabbix-agent state=present

- name: adjust zabbix configuration
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp={{ item.seekfor }} line={{ item.replacewith }} state=present backrefs=yes
  with_items:
    - { seekfor: '^Server=127.0.0.1$', replacewith: 'Server=zabbix.clevertech.biz' }
    - { seekfor: '^ServerActive=127.0.0.1$', replacewith: 'ServerActive=zabbix.clevertech.biz' }
    - { seekfor: '^Hostname=Zabbix\ server$', replacewith: 'Hostname="{{ ansible_hostname }}"' }
  notify:
    - restart zabbix-agent

- name: adjust zabbix agent configuration
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf insertafter='# HostMetadataItem=' line='HostMetadataItem=system.uname' state=present
  notify:
    - restart zabbix-agent

