---

- name: Install Apache
  action: apt name=apache2 state=present

- name: Make sure mod_rewrite is enabled
  command: /usr/sbin/a2enmod rewrite

- name: Start Apache
  service: name=apache2 state=started
