---

- name: Remove apparmor
  action: apt name=apparmor state=absent

- name: Install common packages
  action: apt name={{ item }} state=present
  with_items:
    - python-software-properties
    - screen
    - nano
    - apt-utils
    - mc
    - make
    - cpp
    - curl
    - cron
    - gcc
    - g++
    - git
    - telnet
    - wget
    - htop
    - sendmail
    - ntp
    - graphicsmagick

- name: Check current timezone
  shell: cat /etc/timezone
  register: current_zone

- name: Set timezone variables
  copy: content={{server_timezone}}
          dest=/etc/timezone
          owner=root
          group=root
          mode=0644
          backup=yes
  when: current_zone.stdout != '{{server_timezone}}'
  notify:
    - update timezone

- name: Add user 'travis'
  user: name=travis state=present

- name: Add travis user authorized key
  authorized_key: user=travis key="{{ lookup('file', '../../../../build/ssh/id_rsa.pub') }}"
