# web:
#   build: web/.
#   links:
#     - api
#   ports:
#     - 8080:8080
#   volumes:
#     - ./web/app:/web/app

api:
  build: api/.
  links:
    - redis
    - mongo
    - mysql
  ports:
    - 8081:8081
  volumes:
    - ./api:/api

redis:
  image: redis:3.0.4

mongo:
  image: mongo:3.0.7

mysql:
  image: mysql:5.7.9
  environment:
    MYSQL_ROOT_PASSWORD: password
