---

- name: Add zabbix repo to apt sources list
  template: src=zabbix.list.j2 dest=/etc/apt/sources.list.d/zabbix.list owner=root group=root mode=0644

- name: Add zabbix apt signing key
  apt_key: url=http://repo.zabbix.com/zabbix-official-repo.key state=present

- name: Fetch 10Gen signing key
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10

- name: Add 10Gen repository
  shell:
    echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/10gen.list
    creates=/etc/apt/sources.list.d/10gen.list

- name: Add nginx PPA
  apt_repository: repo='ppa:nginx/stable'

- name: Add nodejs PPA
  apt_repository: repo='ppa:rwky/nodejs'

- name: Add redis PPA
  apt_repository: repo='ppa:chris-lea/redis-server'

- name: Upgrade system
  action: apt upgrade=yes update_cache=yes

