#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

help() {
  echo find unfuckup clear remove build install install_release stop start
  exit
}

cmd=$( basename $0 )
suffix=${cmd#android}
if [ "$suffix" ]; then
  suffix=${cmd#android-}
  shift
  $DIR/android $suffix $*
  exit 0
fi

. $DIR/common.sh
[ "$#" -lt 1 ] && help
stop=1
start=1

for i in $*; do
  case $1 in
    find) find=1 ;;
    stop) start= ;;
    start) stop= ;;
    clear) clear=1 ;; 
    unfuckup) 
      stop=
      start=
      unfuckup=1 ;;
    remove) 
      remove=1 
      start=
    ;;
    build) 
      build=1 
      install=1
    ;;
    install) install=1 ;;
    install_release) install_release=1 ;;
    *)
      echo "$1 not understood"
      help
      ;;
  esac
  shift
done

[ "$find" ] && get_device
[ "$unfuckup" ] && unfuckup
[ "$stop" ] && wrap stop
[ "$clear" ] && wrap clear
[ "$build" ] && build
[ "$remove" ] && wrap uninstall
[ "$install" ] && wrap install $DIR/../platforms/android/build/outputs/apk/android-debug.apk
[ "$install_release" ] && wrap install $DIR/../releases/waivecar.apk
[ "$start" ] && wrap start
