---
- name: Install rtail
  action: npm name=rtail global=yes

- name: Setup rtail-server init script
  template: src=rtail-server.j2 dest=/etc/init.d/rtail owner=root group=root mode=0755
  notify: restart rtail

- name: Setup rtail-client init script
  template: src=rtail-client.j2 dest=/etc/init.d/rtail-client owner=root group=root mode=0755
  notify: restart rtail-client

- name: Ensure rtail start at boot
  service: name=rtail enabled=yes

- name: Ensure rtail-client start at boot
  service: name=rtail-client enabled=yes
