---

- name: Install nginx
  action: apt name=nginx state=present

- name: Install nodejs
  action: apt name=nodejs state=present

- name: Install pm2
  #action: npm name=pm2 global=yes
  command: npm install --unsafe-perm -g pm2

- name: Install grunt
  action: npm name={{ item }} global=yes
  with_items:
    - grunt
    - grunt-cli

- name: Install bower
  action: npm name=bower global=yes

- name: Install jshint
  action: npm name=jshint global=yes

- name: Install anywhere
  action: npm name=anywhere global=yes

- name: Install gulp
  action: npm name=gulp global=yes

- name: Change owner for /opt
  action: file path=/opt owner=travis group=travis

- name: Create application dir
  action: file path=/opt/{{ name }} owner=travis group=travis state=directory

- name: Add Travis to sudoers
  lineinfile: dest=/etc/sudoers
              line="travis ALL=(travis:travis) ALL"
              state=present

- name: Setup logrotate for /opt
  template: src=logrotate.j2 dest=/etc/logrotate.d/opt owner=root group=root mode=0644

- name: Prepare robots.txt for no Google indexing
  template: src=no_index_robots.j2 dest=/opt/no_index_robots.txt owner=www-data group=www-data mode=0644
  notify: reload nginx

- name: Default nginx config
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify: reload nginx

- name: Setup node app init script
  template: src=node-init.j2 dest=/etc/init.d/node-{{ name }} owner=root group=root mode=0755

- name: Ensure node app start at boot
  service: name=node-{{ name }} enabled=yes 
