#!/bin/bash

ix=0
d=`mktemp -d`
while [ "$#" -gt 1 ]; do
  file=$1
  for host in waive-prod1 waive-prod2; do
    scp -C $host:$file $d/$ix
    ix=$(( ix + 1 ))
  done
  shift
done
cat $d/* 
rm -r $d

