- hosts: all
  sudo: yes
  user: ubuntu
    
  roles:
    - { role: backup, when: enable_backup }

  vars:
    backup_target_user: 'aws_access_key'
    backup_target_pass: 'aws_secret_key'
    backup_bucket: 's3_bucket_name'
    backup_mysql_user: 'root'
    backup_mysql_pass: 'mysql_root_password'

    backup_profiles:

    # Backup directory
    - name: files                               # Required params
      schedule: 0 3 * * *                       # At 3am every day
      source: /etc
      target: s3+http://{{backup_bucket}}/{{inventory_hostname}}/etc

    # Backup mysql database
    - name: mysql
      schedule: 0 4 * * *                       # At 4am every day
      source: mysql://mysql              # Backup prefixes: postgresql://, maysql://, mongo://
      target: s3+http://{{backup_bucket}}/{{inventory_hostname}}/mysql

