---
# This script assumes that the server(s) already exists
# This script is idempotent (it can be run every time you need to modify server conf)
#
# Before run, comment unneeded roles 
- name: Playbook for project setup (not tied to a specific server)
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "{{ lookup('env', 'HOME') }}/.ansible_vars.yml"
    - "travis_vars.yml"
  roles:
    - { role: travis, when: exec_travis_role }
- name: Playbook for node server creation and configuration
  hosts: nodeservers
  sudo: yes
  user: ubuntu
  roles:
    - common
    - { role: nodejs+nginx, node_devel: False }
    - mongo
    - redis
#    - java
#    - elasticsearch
    - rtail
    - zabbix
    
- name: Playbook for vagrant node server creation and configuration
  hosts: vagrant
  sudo: yes
  user: vagrant
  roles:
    - common
    - { role: nodejs+nginx, node_devel: False }
    - mongo
    - redis
- name: Playbook for PHP server creation and configuration (not yet finished)
  hosts: phpservers
  sudo: yes
  user: ubuntu
  roles:
    - common
    - php
    - apache
    - mysql
    - zabbix
- name: Playbook for db server creation and configuration
  hosts: dbservers
  sudo: yes
  user: ubuntu
  roles:
    - common
    - mongo
    - redis
    - zabbix
