---

- name: TravisCI - Trigger a GitHub repo sync
  action: uri 
          url=https://api.travis-ci.com/users/sync 
          method=POST
          status_code=200
          HEADER_Accept="application/vnd.travis-ci.2+json"
          HEADER_User-Agent="Ansible"
          HEADER_Authorization="token {{ travis_access_token }}"

- name: TravisCI - Poll until syncing is done
  action: uri 
          url=https://api.travis-ci.com/users/ 
          method=GET
          status_code=200
          HEADER_Accept="application/vnd.travis-ci.2+json"
          HEADER_User-Agent="Ansible"
          HEADER_Authorization="token {{ travis_access_token }}"
  register: result
  until: not result.json.user.is_syncing 
  retries: 100
  delay: 10

- name: TravisCI - Get repo
  action: uri
          url=https://api.travis-ci.com/repos/{{ gitHubRepo }}
          method=GET
          status_code=200
          HEADER_Accept="application/vnd.travis-ci.2+json"
          HEADER_User-Agent="Ansible"
          HEADER_Authorization="token {{ travis_access_token }}"
  register: result

- name: TravisCI - Set payload (activate)
  set_fact: 
    body_json: { "hook": { "id": "{{ result.json.repo.id }}", "active": true } }

- name: TravisCI - Activate repo
  action: uri
          url=https://api.travis-ci.com/hooks/
          method=PUT
          status_code=200
          HEADER_Content-Type="application/json"
          HEADER_Accept="application/vnd.travis-ci.2+json"
          HEADER_User-Agent="Ansible"
          HEADER_Authorization="token {{ travis_access_token }}"
          body='{{ body_json | to_json }}'

- name: TravisCI - Set payload (options)
  set_fact: 
    body_json: { settings: { "builds_only_with_travis_yml": true, "build_pushes": true, "build_pull_requests": true, "maximum_number_of_builds": 1 }}

- name: TravisCI - Set repo options
  action: uri
          url=https://api.travis-ci.com/repos/{{ result.json.repo.id}}/settings
          method=PATCH
          status_code=200
          HEADER_Content-Type="application/json"
          HEADER_Accept="application/vnd.travis-ci.2+json"
          HEADER_User-Agent="Ansible"
          HEADER_Authorization="token {{ travis_access_token }}"
          body='{{ body_json | to_json }}'

- name: Configure Slack-Travis integration
  action: shell travis encrypt --no-interactive  "clevertech:eXTrbmmSJKOcfaPK0Wt93umT{{ slackChannel  }}" --add notifications.slack chdir=../..

- name: Check if SSH key for user travis already exists
  action: stat path=../build/ssh/id_rsa
  register: rsa

- name: Generate a SSH key for user travis
  action: shell ssh-keygen -t rsa -C "travis@{{ name }}" -f deployment/build/ssh/id_rsa -N "" chdir=../..
  when: rsa.stat.exists == False

- name: Encrypt SSH key
  action: shell travis encrypt-file --no-interactive  deployment/build/ssh/id_rsa  deployment/build/ssh/id_rsa.enc --add chdir=../..

- name: chmod SSH key
  action: lineinfile dest=../../.travis.yml regexp="- chmod 400 deployment/build/ssh/id_rsa" insertafter=" -out deployment/build/ssh/id_rsa -d" line="- chmod 400 deployment/build/ssh/id_rsa" 

- name: Remove cleverbuild testing requisites (1)
  action: lineinfile dest=../../.travis.yml regexp="- sudo apt-get update -qq" state=absent  

- name: Remove cleverbuild testing resuisites (2)
  action: lineinfile dest=../../.travis.yml regexp="- sudo apt-get install -qq ansible" state=absent  

- name: Activating Travis CI sudo-false container-based build (fast)
  action: 'lineinfile dest=../../.travis.yml regexp="sudo: false" line="sudo: false" insertafter="language: "'

- name: Creating README.md
  action: template src=readme.j2 dest=../../README.md

- name: Create pm2 init script (dev)
  template: src=dev.pm2.j2 dest=../init/dev.pm2.json 

- name: Create pm2 init script (stag)
  template: src=stag.pm2.j2 dest=../init/stag.pm2.json 

- name: Create pm2 init script (prod)
  template: src=prod.pm2.j2 dest=../init/prod.pm2.json 

- name: TravisCI role has been executed correctly. To save time, I'm deactivating it 
  action: 'lineinfile dest=travis_vars.yml regexp="exec_travis_role" line="exec_travis_role: False"'
 
